version: "3.5"

services:
    pakemon:
        build: .
        ports:
            - "8081:8081"
        networks:
            - pakemon
    
    # these are targets:
    
    nowasp:
        image: citizenstig/nowasp
        hostname: nowasp
        networks:
            - pakemon
    webgoat:
        image: webgoat/webgoat-7.1
        hostname: webgoat
        networks:
            - pakemon
    dvwa:
        image: citizenstig/dvwa
        hostname: dvwa
        networks:
            - pakemon
    securityshepherd:
        image: ismisepaul/securityshepherd
        hostname: securityshepherd
        networks:
            - pakemon
    vaas-cve-2014-0160:
        image: hmlio/vaas-cve-2014-0160
        hostname: vaas-cve-2014-0160
        networks:
            - pakemon
    cve-2017-7494:
        image: vulnerables/cve-2017-7494
        hostname: cve-2017-7494
        networks:
            - pakemon
    vaas-cve-2014-6271:
        image: hmlio/vaas-cve-2014-6271
        hostname: vaas-cve-2014-6271
        networks:
            - pakemon

networks:
    pakemon:
        name: pakemon