version: "3.5"

services:
    # this gives you a CLI to interrogate
    haxor:
        image: kalilinux/kali-rolling
        tty: true
        networks:
            - pakemon
    
    # this is the demo backend
    pakemon:
        image: python:alpine
        ports:
            - 12345:12345/udp
        volumes:
            - ./:/server
        command: python3 /server/server.py
        networks:
            - pakemon
        tty: true

    # these are targets:
    nowasp:
        image: citizenstig/nowasp
        hostname: nowasp
        networks:
            - pakemon
    
    webgoat:
        image: webgoat/webgoat-7.1
        hostname: webgoat
        networks:
            - pakemon
    
    dvwa:
        image: citizenstig/dvwa
        hostname: dvwa
        networks:
            - pakemon
    
    securityshepherd:
        image: ismisepaul/securityshepherd
        hostname: securityshepherd
        networks:
            - pakemon

    vaas-cve-2014-0160:
        image: hmlio/vaas-cve-2014-0160
        hostname: vaas-cve-2014-0160
        networks:
            - pakemon
    cve-2017-7494:
        image: vulnerables/cve-2017-7494
        hostname: cve-2017-7494
        networks:
            - pakemon
    vaas-cve-2014-6271:
        image: hmlio/vaas-cve-2014-6271
        hostname: vaas-cve-2014-6271
        networks:
            - pakemon

# careful, this is a war-zone :)
networks:
    pakemon:
        name: pakemon